

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace wpf_TechMarketMangement.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TechMarketManagementEntities : DbContext
{
    public TechMarketManagementEntities()
        : base("name=TechMarketManagementEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Input> Inputs { get; set; }

    public virtual DbSet<InputInfo> InputInfoes { get; set; }

    public virtual DbSet<Object> Objects { get; set; }

    public virtual DbSet<OuputInfo> OuputInfoes { get; set; }

    public virtual DbSet<Output> Outputs { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    public virtual DbSet<Unit> Units { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<User> Users { get; set; }

}

}

