//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_TechMarketMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OuputInfo
    {
        public int Id { get; set; }
        public int IdObject { get; set; }
        public int IdOutput { get; set; }
        public Nullable<int> Counts { get; set; }
        public Nullable<int> IdCustomer { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Object Object { get; set; }
        public virtual Output Output { get; set; }
    }
}
